# Generated by Django 4.1.2 on 2022-10-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_rename_creater_name_course_creator_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=256)),
                ('test_duration', models.DurationField()),
            ],
        ),
    ]
