# Generated by Django 4.1.2 on 2022-10-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
